version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  hatchet-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run hatchet tests
          command: make hatchet
  unit-test:
    docker:
      - image: heroku/heroku:20-build
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Run unit tests
          command: make unit
  unit-test-heroku-stack:
    parameters:
      stack-number:
        type: "string"
        default: "20"
    docker:
      - image: heroku/heroku:<< parameters.stack-number >>-build
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test heroku-<< parameters.stack-number >>-build
          command: make heroku-<< parameters.stack-number >>-build
  unit-test-binary:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test Go Binary
          command: make test-binary
workflows:
  version: 2
  test:
    jobs:
      - shellcheck/check
      - unit-test-heroku-stack:
          stack-number: "20"
      - unit-test-heroku-stack:
          stack-number: "18"
      - unit-test-heroku-stack:
          stack-number: "16"
      - hatchet-test
      - unit-test
      - unit-test-binary
